{{- define "chart-library.service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
spec:
  selector:
      {{- include "app-labels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.app_port }}
{{- end }}